services:
  - type: web
    name: rendertron
    env: node
    buildCommand: npm install && npm run build
    startCommand: node build/rendertron.js
    envVars:
      - key: NODE_ENV
        value: production

